
pool:
  vmImage: 'macOS-latest' 
  
  
resources: 
  repositories: 
    - repository: andriod_templates
      type: github
      name: Dayanandachari/andriod_templates
      endpoint: https://github.com/Dayanandachari/andriod_templates.git


jobs:
- template: parameter_templates.yml@andriod_templates
  
