
pool:
  vmImage: 'macOS-latest' 
  
  
resources: 
  repositories: 
    - repository: template_test_repo
      type: git
      name: template_test_repo
      

jobs:
- template: sample_template.yml@template_test_repo
  
