
pool:
  vmImage: 'macOS-latest' 
  
  
resources: 
  repositories: 
    - repository: template_test_repo
      type: git
      name: template_test_repo
      

jobs:
- template: parameter_templates.yml@andriod_templates
  
