
trigger: none

resources: 
  repositories: 
    - repository: andriod_templates
      type: github
      name: Dayanandachari/andriod_templates
      endpoint: 'Dayanandachari'

jobs:
- template: parameter_templates.yml@andriod_templates
  parameters:
    employeename: 'daya'  

- template: parameter_templates.yml@andriod_templates
  parameters:
    employeename: 'anad'  
        

  
