
trigger: none

resources: 
  repositories: 
    - repository: andriod_templates
      type: github
      name: Dayanandachari/andriod_templates
      endpoint: github.com

jobs:
- template: andriod_templates/parameter_templates.yml
  parameters:
    employeename: 'daya'  

- template: andriod_templates/parameter_templates.yml
  parameters:
    employeename: 'anad'  
        

  
