
trigger: none

variables:
- group: 'Andriod_variable_group'

resources: 
  repositories: 
    - repository: andriod_templates
      type: github
      name: Dayanandachari/andriod_templates
      endpoint: 'Dayanandachari'

jobs:
- template: parameter_templates.yml@andriod_templates
  parameters:
    employeename: '$(firstname)'

- template: parameter_templates.yml@andriod_templates
  parameters:
    employeename: '$(secondname)'
        

  
