
trigger: none

variables:
- group: 'Andriod_variable_group'

resources: 
  repositories: 
    - repository: andriod_templates
      type: github
      name: Dayanandachari/andriod_templates
      endpoint: 'Dayanandachari'

jobs: 
- job: employeename
  steps: 
  - template: parameter_templates.yml@andriod_templates
    parameters:
      employeename: '$(first_name)'

  - template: parameter_templates.yml@andriod_templates
    parameters:
      employeename: '$(second_name)'
        

  
